// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZqyV1uXwUKp8RSx3Pf6X5VGCq-EFPYGs',
    appId: '1:442583590864:web:ed0702cc9a45c768e0bbd5',
    messagingSenderId: '442583590864',
    projectId: 'subcription-milk',
    authDomain: 'subcription-milk.firebaseapp.com',
    storageBucket: 'subcription-milk.appspot.com',
    measurementId: 'G-9GP4DG31M2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUL2jswECaLXo2SmbtLYCyTiBRLGFld3Y',
    appId: '1:442583590864:android:635c0bb4de6decede0bbd5',
    messagingSenderId: '442583590864',
    projectId: 'subcription-milk',
    storageBucket: 'subcription-milk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUT6mcAimq35sPaZxCMEKmHYzVqBrt75M',
    appId: '1:442583590864:ios:ae2f494578552767e0bbd5',
    messagingSenderId: '442583590864',
    projectId: 'subcription-milk',
    storageBucket: 'subcription-milk.appspot.com',
    androidClientId: '442583590864-2frjl37hm82tbm5s8lksmo60o77f9deu.apps.googleusercontent.com',
    iosClientId: '442583590864-fqoiqukcprs071tv333u0fvtjuk2ugbu.apps.googleusercontent.com',
    iosBundleId: 'com.example.subscriptionMilk',
  );
}
